# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :register_new_devices do
    register_devices(
      devices_file: "./fastlane/devices.txt",
      team_id: "ABCDEFG"
    )
  end

  desc "Get certificates"
  lane :certificates do
    app_store_connect_api_key(
      key_id: ENV['API_KEY_ID'],
      issuer_id: ENV['API_ISSUER_ID'],
      key_content: ENV['API_PRIVATE_KEY'],
      duration: 500,
      in_house: false
    )
    
    ENV['MATCH_GIT_PRIVATE_KEY'] = "https://github.com/chansooo/GongCert"
    sync_code_signing(
      type: "appstore",
      app_identifier: BundleId,
      readonly: false
    )
  end
  
  # error do |lane, exception, options|
  #   slack(
	#   message: "App Store Connect - Error detected: #{exception}",
  #     success: false,
	#   slack_url: ENV['SLACK_URL']
	# )
  # end
end
